/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fypmanagement;

/**
 *
 * @author Munawar Ali
 */
import java.util.*;
import javax.swing.JOptionPane;
public class AdminMenu extends javax.swing.JFrame {

    /**
     * Creates new form AdminMenu
     */
    public AdminMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        AddStd1 = new javax.swing.JButton();
        delStd1 = new javax.swing.JButton();
        listOfStd1 = new javax.swing.JButton();
        logout1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        addPro1 = new javax.swing.JButton();
        delPro1 = new javax.swing.JButton();
        updPro1 = new javax.swing.JButton();
        listOfProject1 = new javax.swing.JButton();
        logout3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        addAdv1 = new javax.swing.JButton();
        delAdv1 = new javax.swing.JButton();
        listOfAdvisor1 = new javax.swing.JButton();
        logout2 = new javax.swing.JButton();
        updAdv1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Menu");

        jTabbedPane1.setBackground(new java.awt.Color(0, 0, 0));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        AddStd1.setBackground(new java.awt.Color(51, 51, 51));
        AddStd1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        AddStd1.setForeground(new java.awt.Color(255, 255, 255));
        AddStd1.setText("Add Student");
        AddStd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStd1ActionPerformed(evt);
            }
        });

        delStd1.setBackground(new java.awt.Color(51, 51, 51));
        delStd1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        delStd1.setForeground(new java.awt.Color(255, 255, 255));
        delStd1.setText("Delete Student");
        delStd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delStd1ActionPerformed(evt);
            }
        });

        listOfStd1.setBackground(new java.awt.Color(51, 51, 51));
        listOfStd1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        listOfStd1.setForeground(new java.awt.Color(255, 255, 255));
        listOfStd1.setText("List of Students");
        listOfStd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listOfStd1ActionPerformed(evt);
            }
        });

        logout1.setBackground(new java.awt.Color(255, 0, 0));
        logout1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        logout1.setForeground(new java.awt.Color(255, 255, 255));
        logout1.setText("Logout");
        logout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout1ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Students");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(delStd1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddStd1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(listOfStd1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(logout1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(AddStd1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delStd1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listOfStd1)
                .addGap(36, 36, 36)
                .addComponent(logout1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        jTabbedPane1.addTab("Student", jPanel1);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Manage Projects");

        addPro1.setBackground(new java.awt.Color(51, 51, 51));
        addPro1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        addPro1.setForeground(new java.awt.Color(255, 255, 255));
        addPro1.setText("Add Project");
        addPro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPro1ActionPerformed(evt);
            }
        });

        delPro1.setBackground(new java.awt.Color(51, 51, 51));
        delPro1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        delPro1.setForeground(new java.awt.Color(255, 255, 255));
        delPro1.setText("Delete Project");
        delPro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delPro1ActionPerformed(evt);
            }
        });

        updPro1.setBackground(new java.awt.Color(51, 51, 51));
        updPro1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        updPro1.setForeground(new java.awt.Color(255, 255, 255));
        updPro1.setText("Update Project");
        updPro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updPro1ActionPerformed(evt);
            }
        });

        listOfProject1.setBackground(new java.awt.Color(51, 51, 51));
        listOfProject1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        listOfProject1.setForeground(new java.awt.Color(255, 255, 255));
        listOfProject1.setText("List of Projects");
        listOfProject1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listOfProject1ActionPerformed(evt);
            }
        });

        logout3.setBackground(new java.awt.Color(255, 0, 0));
        logout3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        logout3.setForeground(new java.awt.Color(255, 255, 255));
        logout3.setText("Logout");
        logout3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(delPro1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(212, 212, 212)
                            .addComponent(addPro1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(listOfProject1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updPro1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(logout3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel3)
                .addGap(33, 33, 33)
                .addComponent(addPro1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delPro1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updPro1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listOfProject1)
                .addGap(34, 34, 34)
                .addComponent(logout3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Project", jPanel3);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        addAdv1.setBackground(new java.awt.Color(51, 51, 51));
        addAdv1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        addAdv1.setForeground(new java.awt.Color(255, 255, 255));
        addAdv1.setText("Add Advisor");
        addAdv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAdv1ActionPerformed(evt);
            }
        });

        delAdv1.setBackground(new java.awt.Color(51, 51, 51));
        delAdv1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        delAdv1.setForeground(new java.awt.Color(255, 255, 255));
        delAdv1.setText("Delete Advisor");
        delAdv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delAdv1ActionPerformed(evt);
            }
        });

        listOfAdvisor1.setBackground(new java.awt.Color(51, 51, 51));
        listOfAdvisor1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        listOfAdvisor1.setForeground(new java.awt.Color(255, 255, 255));
        listOfAdvisor1.setText("List of Advisors");
        listOfAdvisor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listOfAdvisor1ActionPerformed(evt);
            }
        });

        logout2.setBackground(new java.awt.Color(255, 0, 0));
        logout2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        logout2.setForeground(new java.awt.Color(255, 255, 255));
        logout2.setText("Logout");
        logout2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout2ActionPerformed(evt);
            }
        });

        updAdv1.setBackground(new java.awt.Color(51, 51, 51));
        updAdv1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        updAdv1.setForeground(new java.awt.Color(255, 255, 255));
        updAdv1.setText("Update Advisor");
        updAdv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updAdv1ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Manage Advisor");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(addAdv1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(listOfAdvisor1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(delAdv1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updAdv1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(161, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(logout2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel2)
                .addGap(39, 39, 39)
                .addComponent(addAdv1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delAdv1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updAdv1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listOfAdvisor1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(logout2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        jTabbedPane1.addTab("Advisor", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AddStd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStd1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        AddStudent addStdFrame = new AddStudent();
        addStdFrame.setVisible(true);
    }//GEN-LAST:event_AddStd1ActionPerformed

    private void delStd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delStd1ActionPerformed
        // TODO add your handling code here:
        DeleteStudent delStdFrame = new DeleteStudent();
        this.setVisible(false);
        delStdFrame.setVisible(true);
    }//GEN-LAST:event_delStd1ActionPerformed

    private void listOfStd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listOfStd1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ListOfStudents main = new ListOfStudents();
        main.setVisible(true); 
    }//GEN-LAST:event_listOfStd1ActionPerformed

    private void logout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MainMenu main = new MainMenu();
        main.setVisible(true); 
    }//GEN-LAST:event_logout1ActionPerformed

    private void addAdv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAdv1ActionPerformed
        // TODO add your handling code here:
        AddAdvisor addAdv = new AddAdvisor();
        this.setVisible(false);
        addAdv.setVisible(true);
    }//GEN-LAST:event_addAdv1ActionPerformed

    private void delAdv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delAdv1ActionPerformed
        // TODO add your handling code here:
        DeleteAdvisor delAdv = new DeleteAdvisor();
        this.setVisible(false);
        delAdv.setVisible(true);
    }//GEN-LAST:event_delAdv1ActionPerformed

    private void listOfAdvisor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listOfAdvisor1ActionPerformed
        // TODO add your handling code here:
        ListOfAdvisors advMenu = new ListOfAdvisors();
        this.setVisible(false);
        advMenu.setVisible(true);
    }//GEN-LAST:event_listOfAdvisor1ActionPerformed

    private void logout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MainMenu main = new MainMenu();
        main.setVisible(true); 
    }//GEN-LAST:event_logout2ActionPerformed

    private void updAdv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updAdv1ActionPerformed
        // TODO add your handling code here:
        UpdateAdvisor advMenu = new UpdateAdvisor();
        this.setVisible(false);
        advMenu.setVisible(true);
    }//GEN-LAST:event_updAdv1ActionPerformed

    private void addPro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPro1ActionPerformed
        AddProject addPro = new AddProject();
        this.setVisible(false);
        addPro.setVisible(true);
    }//GEN-LAST:event_addPro1ActionPerformed

    private void delPro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delPro1ActionPerformed
        // TODO add your handling code here:
        DeleteProject delPro = new DeleteProject();
        this.setVisible(false);
        delPro.setVisible(true);
    }//GEN-LAST:event_delPro1ActionPerformed

    private void updPro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updPro1ActionPerformed
        // TODO add your handling code here:
        UpdateProject delPro = new UpdateProject();
        this.setVisible(false);
        delPro.setVisible(true);

    }//GEN-LAST:event_updPro1ActionPerformed

    private void listOfProject1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listOfProject1ActionPerformed
        // TODO add your handling code here:
        ListOfProjects listPro = new ListOfProjects();
        this.setVisible(false);
        listPro.setVisible(true);
    }//GEN-LAST:event_listOfProject1ActionPerformed

    private void logout3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MainMenu main = new MainMenu();
        main.setVisible(true); 
    }//GEN-LAST:event_logout3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddStd1;
    private javax.swing.JButton addAdv1;
    private javax.swing.JButton addPro1;
    private javax.swing.JButton delAdv1;
    private javax.swing.JButton delPro1;
    private javax.swing.JButton delStd1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton listOfAdvisor1;
    private javax.swing.JButton listOfProject1;
    private javax.swing.JButton listOfStd1;
    private javax.swing.JButton logout1;
    private javax.swing.JButton logout2;
    private javax.swing.JButton logout3;
    private javax.swing.JButton updAdv1;
    private javax.swing.JButton updPro1;
    // End of variables declaration//GEN-END:variables
}
